version: "3.8"
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config.py:/app/config.py
      - ./bot.py:/app/bot.py
    environment:
      - PYTHONPATH=/app
